### ISSUE TITLE
font file corrupt in v1.0.1

### ISSUE THREAD

**Issue by Teamshake** [MakeMHz/xbox-hdmi-app#2]
RobotoMono-Regular.ttf in v1.0.1 appears to be corrupt.  Get an error on launch that it cannot load the font.  using assets folder from v1.0.0 with default.xbe from v1.0.1 loads normallly

**Comment by DarkGabbz** [comment]
I experience the same issue.

**Comment by dracc** [comment]
`md5sum` of the font file in the release doesn't match that of the git repository.
Release: `b824d71ec99481c207f346c643383173`
Git repo: `a48ac41620cd818c5020d0f4302489ff`

---
Edit:
Seems the whole assets folder of the release is corrupt - if you replace just the font file, the image files fail to load too.
